package com.voicedemo.gateway.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "voice")
public record ModeProperties(
        String runtime,
        String moshiMode,
        String moshiWsUrl,
        String sttMode,
        String sttUrl,
        double sttEnergyThreshold,
        int sttMinSpeechMs,
        int sttSilenceMs,
        int sttMaxUtteranceMs,
        String ttsMode,
        String ttsUrl,
        String llmMode,
        String llmBaseUrl,
        String llmApiKey,
        String llmModelAnswer,
        String llmModelRouter,
        String fastLlmMode,
        String fastLlmBaseUrl,
        String fastLlmApiKey,
        String fastLlmModel,
        int fastReplyMaxTokens,
        double fastReplyTemperature,
        int fastPendingMaxWords,
        int fastStaleUtteranceMs,
        int askTimeoutMs,
        int staleTurnLimit,
        String eventLogPath,
        int suppressionTokenThreshold,
        int suppressionFadeMs,
        int bargeInMinMs,
        double bargeInEnergyThreshold,
        int stubTtsFrameCount,
        String wsBearerToken,
        int llmMaxRetries,
        int llmRetryBackoffMs,
        int sidecarStartupRetries,
        int sidecarStartupBackoffMs,
        int sidecarHealthTimeoutMs) {
}
