package com.voicedemo.gateway.session;

public enum SessionEvent {
    CLIENT_AND_MOSHI_OPEN,
    USER_UTTERANCE,
    ROUTER_CHAT,
    MOSHI_AUDIO_STARTS,
    MOSHI_AUDIO_IDLE,
    ROUTER_ASK,
    ROUTER_ASK_PENDING,
    FAST_REPLY_REQUESTED,
    FAST_REPLY_READY,
    BACKEND_ANSWER_READY,
    BACKEND_INJECT_STARTED,
    JOB_RESULT_FRESH,
    JOB_RESULT_STALE_REINTRODUCE,
    JOB_RESULT_STALE_DROP,
    JOB_TIMEOUT,
    TTS_STREAM_ENDS,
    USER_SPEECH,
    MOSHI_WS_DROP
}
